# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    file_data_source.csv.questions: '../FileDataSource/csv/questions.csv'
    file_data_source.json.questions: '../FileDataSource/json/questions.json'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    #Default question data extractor
    App\DataExtractor\QuestionEntityDataExtractorInterface: '@App\DataExtractor\QuestionCsvEntityExtractor'

    #Default question data source
    App\DataSource\QuestionsDataSourceInterface: '@App\DataSource\QuestionCsvDataSource'

    'App\DataProvider\QuestionFileCollectionDataProvider':
        tags: [ { name: 'api_platform.collection_data_provider', priority: 1 } ]
        # Autoconfiguration must be disabled to set a custom priority
        autoconfigure: false

